name: setup_test

on: [push, pull_request, workflow_dispatch]
paths-ignore: '**.md'

jobs:
  build:
    
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: setup ROS
        run: |
          bash ./Setup/setup_ros.bash
      - name: setup simulator
        run: |
          bash ./Setup/setup_simulator.bash
