name: setup_test

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: setup
        run: |
          ./Setup/setup_ros.bash
          ./Setup/setup_simulator.bash
